"""Flask backend for Neura Connect telemetry processing."""

from __future__ import annotations
import threading
from typing import Any
import pyttsx3
from flask import Flask, jsonify, request
from flask_cors import CORS

from cloud_logic import sync_device_payload

app = Flask(__name__)
CORS(app) 

# EWMV/TRM parameters
ALPHA = 0.2
VARIANCE_THRESHOLD = 2.5
COOLDOWN_PACKETS = 40  # Wait ~2 seconds before triggering another API call

trm_state = {
    "initialized": False,
    "ew_mean": 0.0,
    "ew_variance": 0.0,
    "cooldown": 0
}

# Global state for the React UI to read
dashboard_state = {
    "status": "STANDBY",
    "z": 0.0,
    "variance": 0.0,
    "cloud_response": None
}

def update_ewmv(sample_z: float, alpha: float = ALPHA) -> tuple[float, float]:
    """Cursor's elegant EWMV math function."""
    if not trm_state["initialized"]:
        trm_state["initialized"] = True
        trm_state["ew_mean"] = sample_z
        trm_state["ew_variance"] = 0.0
        return trm_state["ew_mean"], trm_state["ew_variance"]

    prev_mean = trm_state["ew_mean"]
    prev_var = trm_state["ew_variance"]

    ew_mean = alpha * sample_z + (1.0 - alpha) * prev_mean
    ew_variance = (1.0 - alpha) * (prev_var + alpha * (sample_z - prev_mean) ** 2)

    trm_state["ew_mean"] = ew_mean
    trm_state["ew_variance"] = ew_variance
    return ew_mean, ew_variance

def speak_warning_async(message: str) -> None:
    """Speaks the DYNAMIC text from the AI on a background thread."""
    def _speak() -> None:
        try:
            engine = pyttsx3.init()
            engine.setProperty('rate', 170) # Slightly slower for clinical tone
            engine.say(message)
            engine.runAndWait()
        except Exception as e:
            print(f"Audio Error: {e}")

    threading.Thread(target=_speak, daemon=True).start()

def _extract_z(payload: dict[str, Any]) -> float:
    """Cursor's robust JSON extraction logic."""
    if "z" in payload:
        return float(payload["z"])
    accel = payload.get("accelerometer")
    if isinstance(accel, dict) and "z" in accel:
        return float(accel["z"])
    # Support for standard Sensor Logger arrays
    if "payload" in payload and isinstance(payload["payload"], list):
        for item in payload["payload"]:
            if item.get("name") == "accelerometer":
                return float(item["values"]["z"])
                
    raise ValueError("Missing z-axis accelerometer value.")

@app.post("/data")
def ingest_data():
    global dashboard_state
    
    payload = request.get_json(silent=True)
    if not isinstance(payload, dict):
        return jsonify({"error": "Invalid or missing JSON body."}), 400

    try:
        z_value = _extract_z(payload)
    except (TypeError, ValueError) as exc:
        return jsonify({"error": str(exc)}), 400

    mean, variance = update_ewmv(z_value)
    
    # Update global state for the React UI
    dashboard_state["z"] = z_value
    dashboard_state["variance"] = variance

    # Handle the Cooldown Timer
    if trm_state["cooldown"] > 0:
        trm_state["cooldown"] -= 1
        return jsonify({"status": "cooling_down"}), 200

    # Trigger Logic
    anomaly = variance > VARIANCE_THRESHOLD

    if anomaly:
        print(f"\n🚨 TREMOR DETECTED! Variance: {variance:.2f}")
        trm_state["cooldown"] = COOLDOWN_PACKETS # Start cooldown
        
        event_payload = {"value": variance}
        
        # Call the Cloud Brain
        cloud_response = sync_device_payload(event_payload)
        
        # Update UI state
        dashboard_state["status"] = "ALERT"
        dashboard_state["cloud_response"] = cloud_response
        
        # Extract the dynamic audio generated by Featherless AI
        dynamic_audio = cloud_response.get("triage", {}).get(
            "audio_instruction", "Warning. Neura Connect detected an anomaly."
        )
        speak_warning_async(dynamic_audio)

    return jsonify({"status": "ok", "anomaly": anomaly}), 200

@app.get("/status")
def get_status():
    """CRITICAL: The React Dashboard needs this route to fetch live data."""
    return jsonify(dashboard_state)

if __name__ == "__main__":
    # debug=False is mandatory when using pyttsx3, or Flask will crash the audio drivers!
    app.run(host="0.0.0.0", port=5000, debug=False)